name: 'pion'
version: '1.0.0'
config-version: 2

profile: 'pion'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pion:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: staging  

    intermediate:
      +materialized: table
      +schema: intermediate 

    marts:
      +materialized: table
      +schema: marts  
      +contract:
        enforced: true
